Add assume role to allowed parameters for s3
bsm/bfs.rb pull request #35
Opened 2021-05-26 16:07 UTC by vrih

Still some debugging to do on this. Will add comments.

2021-05-26 16:08 UTC, vrih commented
https://github.com/bsm/bfs.rb/blob/5b10f5d2bbb592ad64755c96d0638b102f23a9f3/s3/lib/bfs/bucket/s3.rb#L145 is the problematic area. On an assume rule it's empty so it fails for having no credentials. If you remove it and just allow a new STS::Client to be created then it uses the correct role but that role isn't authorised to assume role. I've confirmed locally that I can hope through that role to assume the correct role. I suspect there's some combination of values to pass through as credentials but I just can't find it.

2021-05-27 08:52 UTC, dim requested changes

2021-05-27 08:52 UTC, dim commented on s3/lib/bfs/bucket/s3.rb
> -          client: Aws::STS::Client.new(credentials: config[:credentials]),
```
client: config[:credentials] ? Aws::STS::Client.new(credentials: config[:credentials]) : nil,
```

2021-05-27 08:52 UTC, dim commented on s3/lib/bfs/bucket/s3.rb
> +          role_session_name: SecureRandom.urlsafe_base64(12).to_s,
remove `.to_s`

2021-05-27 09:04 UTC, dim approved these changes

2021-05-27 09:04 UTC, merged